[project]
name = "nerfinternals"
version = "0.1.1"

dependencies = [
    "nerfstudio=0.2.1" # you may want to consider pinning the version, ie "nerfstudio==0.1.19"
]

[tool.setuptools.packages.find]
include = ["nerfinternals*"]

[project.entry-points.'nerfstudio.method_configs']
internals_nerf_blender = 'nerfinternals.internals_config:activation_nerf_blender'
