[project]
name = "nerfinternals"

dependencies = [
    "nerfstudio" # you may want to consider pinning the version, ie "nerfstudio==0.1.19"
]

[tool.setuptools.packages.find]
include = ["nerfinternals*"]

[project.entry-points.'nerfstudio.method_configs']
my-method = 'nerfinternals.config:nerfinternals'
